version: "3.8"

services:
  mysql:
    container_name: mysql
    image: mysql:5.6
    restart: always
    volumes:        #挂载当前的data目录到容器默认mysql存储目录
      - ./mysql/mydir:/mydir
      - ./mysql/datadir:/var/lib/mysql
      - ./mysql/conf/my.cnf:/etc/my.cnf
      #      数据库还原目录 可将需要还原的sql文件放在这里
      - ./mysql/docker/source:/docker-entrypoint-initdb.d
    environment:                        #环境变量
      MYSQL_USER: qzr
      MYSQL_PASS: 66668888
      MYSQL_ROOT_PASSWORD: 66668888    #mysql的root密码
      MYSQL_DATABASE: page     #mysql的初始化数据库
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/logs:/logs
    expose:
      - 6379
    ports:
      - 6379:6379
    environment:
      TZ: Asia/Shanghai
  app:
    container_name: app
    image: node:16-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 7009:7009
    depends_on:
      - mysql
    environment:
      TZ: Asia/Shanghai
    command: yarn start:dev
